[[section-solution-strategy]]
== Estrategia de la solución

[role="arc42help"]
****
.Contents

Para el desarrollo de este proyecto viene impuesta como restricción el uso de React, TypeScript y SOLID. No hay imposición en cuanto a la base de datos a utilizar. Se ha decidito optar por seguir la arquitectura MERN. Es un conjunto de marcos/tecnologías utilizados para el desarrollo web de aplicaciones que consta de MongoDB, React, Express y Node.js como sus componentes.

Para el Front-End se ha utilizado React, una librería desarrollada y mantenida por Facebook. El elemento más importante de React es el componente, que es en esencia una pieza de la interfaz de usuario. Al diseñar una aplicación con React, lo que estamos haciendo es crear componentes independientes y reusables que nos permiten crear interfaces de usuario más complejas.

El uso de MongoDB como base de datos supone una ventaja, debido a que en otras asignaturas de la carrera como SDI ya se ha utilizado esta plataforma.

Node.js es un entorno de ejecución que permite la ejecutar programas escritos en JavaScritp. Utiliza una arquitectura de E/S basada en eventos y sin bloqueos, lo que ayuda a que la aplicación sea escalable y rápida. 

Express es un framework para crear aplicaciones web, APIs y web services. Así como Node.js está destinado a ejecutar JavaScript del lado servidor, pero no para desarrollar sitios web, Express está destinado a esto precisamente.

Para conseguir la máxima disponibilidad de la aplicación en lugar de usar servidores propietarios se desplegará en la nube mediante el uso de Heroku.

La privacidad de los datos de los usuarios se garantizará con la utilización de SOLID, que es una especificación que permite a los usuarios guardar sus datos en almacenes descentralizados llamados PODs. 
****
