[[section-design-decisions]]
== Decisiones de Diseño
 
=== MongoDb
MongoDB es un sistema de base de datos NoSQL, orientado a documentos y 
de código abierto. En lugar de guardar los datos en tablas, tal y como se hace en las bases 
de datos relacionales, MongoDB guarda estructuras de datos BSON (una especificación 
similar a JSON) con un esquema dinámico, haciendo que la integración de los datos en 
ciertas aplicaciones sea más fácil y rápida. MongoDB es una base de datos adecuada para 
su uso en producción y con múltiples funcionalidades.

=== Git - Control de versiones

Se ha utilizado git para realizar el control de versiones. Con git, he trabajado sobre la rama "master".
Sobre ella se han creado subramas con nombres del formato "UOXXXXXX-<cambio a realizar>".
Una vez terminada esa subrama realizaremos un merge sobre master.

Git es una herramienta que nos sirve de mucha utilidad para evitar conflictos.

=== React - Front-End

"User Interface" creada a partir de React, herramienta que ayuda a crear
interfaces de usuario interactivas de forma sencilla diseñando vistas simples para cada estado
en el que se encuentre la aplicación. Permite crear componentes encapsulados
que manejen su propio estado, para convertirlos en interfaces de usuario más complejas.
